version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    expose:
      - '5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ktaxes
    restart: always
    volumes:
      - ./pkg/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ktax-network

  # ktax_api:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #     # args:
  #     #   DATABASE_URL: ${DATABASE_URL}
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "8080:8080"
  #   expose:
  #     - '8080'
  #   networks:
  #     - ktax-network

networks:
    ktax-network: